export const data = [
    {
        title: "المواد الأساسية",
        products: [
            { id: 28, name: "سكر", quantity: 1, unit: "كغ", minPrice: 5000, usdPrice: 0, avgPrice: 5500, image: "/sugar.png", brand: "المنار" },
            { id: 29, name: "رز", quantity: 1, unit: "كغ", minPrice: 7000, usdPrice: 0, avgPrice: 7500, image: "/rice.png", brand: "العنبر" },
            { id: 30, name: "عدس", quantity: 1, unit: "كغ", minPrice: 4000, usdPrice: 0, avgPrice: 4500, image: "/lentils.png", brand: "غير محدد" },
            { id: 31, name: "حمص", quantity: 1, unit: "كغ", minPrice: 5000, usdPrice: 0, avgPrice: 5500, image: "/chickpeas.png", brand: "غير محدد" },
            { id: 32, name: "فاصوليا", quantity: 1, unit: "كغ", minPrice: 6000, usdPrice: 0, avgPrice: 6500, image: "/beans.png", brand: "غير محدد" },
            { id: 33, name: "طحين", quantity: 1, unit: "كغ", minPrice: 3000, usdPrice: 0, avgPrice: 3500, image: "/flour.png", brand: "الوفير" },
            { id: 34, name: "زيت نباتي", quantity: 1, unit: "لتر", minPrice: 10000, usdPrice: 0, avgPrice: 11000, image: "/vegetable_oil.png", brand: "زيتون" },
            { id: 35, name: "شاي", quantity: 1, unit: "غرام", minPrice: 12000, usdPrice: 0, avgPrice: 13000, image: "/tea.png", brand: "ليبتون" },
            { id: 36, name: "قهوة", quantity: 1, unit: "غرام", minPrice: 15000, usdPrice: 0, avgPrice: 16000, image: "/coffee.png", brand: "نستله" },
            { id: 44, name: "معكرونة", quantity: 1, unit: "كغ", minPrice: 4000, usdPrice: 0, avgPrice: 4500, image: "/pasta.png", brand: "باريلا" },
            { id: 45, name: "صلصة طماطم", quantity: 1, unit: "لتر", minPrice: 3000, usdPrice: 0, avgPrice: 3500, image: "/tomato_sauce.png", brand: "غير محدد" },
        ],
    },
    {
        title: "المحروقات",
        products: [
            {
                id: 61,
                name: "بنزين",
                quantity: 1,
                unit: "لتر",
                minPrice: 3000, usdPrice: 0,
                avgPrice: 3500,
                image: "/benzine.png",
                brand: "غير محدد",
            },
            {
                id: 62,
                name: "مازوت",
                quantity: 1,
                unit: "لتر",
                minPrice: 2000,
                usdPrice: 0,
                avgPrice: 2200,
                image: "/diesel.png",
                brand: "غير محدد",
            },
            {
                id: 63,
                name: "غاز",
                quantity: 1,
                unit: "عبوة",
                minPrice: 2000,
                usdPrice: 0,
                avgPrice: 2200,
                image: "/gas.png",
                brand: "غير محدد",
            },
        ],
    },
    {
        title: "اللحوم",
        products: [
            { id: 1, name: "لحم غنم", quantity: 1, unit: "كغ", minPrice: 50000, usdPrice: 0, avgPrice: 55000, image: "/meat1.png", brand: "غير محدد" },
            { id: 2, name: "لحم عجل", quantity: 1, unit: "كغ", minPrice: 40000, usdPrice: 0, avgPrice: 45000, image: "/meat2.png", brand: "غير محدد" },
            { id: 3, name: "فخذ فروج", quantity: 1, unit: "كغ", minPrice: 12000, usdPrice: 0, avgPrice: 13000, image: "/chicken_leg.png", brand: "دجاج الوطن" },
            { id: 4, name: "صدر فروج", quantity: 1, unit: "كغ", minPrice: 15000, usdPrice: 0, avgPrice: 16000, image: "/chicken_breast.png", brand: "دجاج الوطن" },
            { id: 5, name: "جوانح فروج", quantity: 1, unit: "كغ", minPrice: 9000, usdPrice: 0, avgPrice: 10000, image: "/chicken_wings.png", brand: "دجاج الوطن" },
            { id: 6, name: "دبوس فروج", quantity: 1, unit: "كغ", minPrice: 11000, usdPrice: 0, avgPrice: 12000, image: "/chicken_drumstick.png", brand: "دجاج الوطن" },
            { id: 37, name: "لحم ديك رومي", quantity: 1, unit: "كغ", minPrice: 30000, usdPrice: 0, avgPrice: 32000, image: "/turkey_meat.png", brand: "تركي فاخر" },
        ],
    },
    {
        title: "مشتقات الألبان والأجبان",
        products: [
            { id: 61, name: "بيض", quantity: 1, unit: "طبق", minPrice: 5000, usdPrice: 0, avgPrice: 5500, image: "/onion.png", brand: "غير محدد" },
            { id: 7, name: "حليب", quantity: 1, unit: "لتر", minPrice: 2000, usdPrice: 0, avgPrice: 2500, image: "/milk.png", brand: "مراعي" },
            { id: 8, name: "جبنة بيضاء", quantity: 1, unit: "كغ", minPrice: 8000, usdPrice: 0, avgPrice: 9000, image: "/cheese.png", brand: "كفرعسل" },
            { id: 9, name: "لبن", quantity: 1, unit: "لتر", minPrice: 5000, usdPrice: 0, avgPrice: 5500, image: "/yogurt.png", brand: "أبو قوسين" },
            { id: 10, name: "زبدة", quantity: 1, unit: "كغ", minPrice: 10000, usdPrice: 0, avgPrice: 11000, image: "/butter.png", brand: "نادك" },
            { id: 11, name: "قشطة", quantity: 1, unit: "كغ", minPrice: 12000, usdPrice: 0, avgPrice: 13000, image: "/cream.png", brand: "الصافي" },
            { id: 38, name: "جبنة شيدر", quantity: 1, unit: "كغ", minPrice: 12000, usdPrice: 0, avgPrice: 13000, image: "/cheddar_cheese.png", brand: "كفرعسل" },
            { id: 39, name: "جبنة موزاريلا", quantity: 1, unit: "كغ", minPrice: 15000, usdPrice: 0, avgPrice: 16000, image: "/mozzarella_cheese.png", brand: "غير محدد" },
        ],
    },
    {
        title: "الفواكه",
        products: [
            { id: 12, name: "تفاح", quantity: 1, unit: "كغ", minPrice: 3000, usdPrice: 0, avgPrice: 3500, image: "/apple.png", brand: "غير محدد" },
            { id: 13, name: "برتقال", quantity: 1, unit: "كغ", minPrice: 2500, usdPrice: 0, avgPrice: 2800, image: "/orange.png", brand: "غير محدد" },
            { id: 14, name: "موز", quantity: 1, unit: "كغ", minPrice: 4000, usdPrice: 0, avgPrice: 4500, image: "/banana.png", brand: "غير محدد" },
            { id: 15, name: "عنب", quantity: 1, unit: "كغ", minPrice: 5000, usdPrice: 0, avgPrice: 5500, image: "/grapes.png", brand: "غير محدد" },
            { id: 16, name: "رمان", quantity: 1, unit: "كغ", minPrice: 6000, usdPrice: 0, avgPrice: 6500, image: "/pomegranate.png", brand: "غير محدد" },
            { id: 17, name: "خوخ", quantity: 1, unit: "كغ", minPrice: 4500, usdPrice: 0, avgPrice: 5000, image: "/peach.png", brand: "غير محدد" },
            { id: 18, name: "فراولة", quantity: 1, unit: "كغ", minPrice: 7000, usdPrice: 0, avgPrice: 7500, image: "/strawberry.png", brand: "غير محدد" },
            { id: 40, name: "كيوي", quantity: 1, unit: "كغ", minPrice: 8000, usdPrice: 0, avgPrice: 8500, image: "/kiwi.png", brand: "غير محدد" },
            { id: 41, name: "مانجو", quantity: 1, unit: "كغ", minPrice: 10000, usdPrice: 0, avgPrice: 11000, image: "/mango.png", brand: "غير محدد" },
        ],
    },
    {
        title: "الخضار الأساسية",
        products: [
            { id: 19, name: "بطاطا", quantity: 1, unit: "كغ", minPrice: 2000, usdPrice: 0, avgPrice: 2200, image: "/potato.png", brand: "غير محدد" },
            { id: 20, name: "طماطم", quantity: 1, unit: "كغ", minPrice: 1500, usdPrice: 0, avgPrice: 1800, image: "/tomato.png", brand: "غير محدد" },
            { id: 21, name: "بصل", quantity: 1, unit: "كغ", minPrice: 1200, usdPrice: 0, avgPrice: 1400, image: "/onion.png", brand: "غير محدد" },
            { id: 22, name: "ثوم", quantity: 1, unit: "كغ", minPrice: 8000, usdPrice: 0, avgPrice: 9000, image: "/garlic.png", brand: "غير محدد" },
            { id: 23, name: "خيار", quantity: 1, unit: "كغ", minPrice: 2500, usdPrice: 0, avgPrice: 2800, image: "/cucumber.png", brand: "غير محدد" },
            { id: 24, name: "جزر", quantity: 1, unit: "كغ", minPrice: 2000, usdPrice: 0, avgPrice: 2300, image: "/carrot.png", brand: "غير محدد" },
            { id: 25, name: "فليفلة", quantity: 1, unit: "كغ", minPrice: 3500, usdPrice: 0, avgPrice: 4000, image: "/pepper.png", brand: "غير محدد" },
            { id: 26, name: "بقدونس", quantity: 1, unit: "حزمة", minPrice: 500, usdPrice: 0, avgPrice: 700, image: "/parsley.png", brand: "غير محدد" },
            { id: 27, name: "سبانخ", quantity: 1, unit: "كغ", minPrice: 1500, usdPrice: 0, avgPrice: 1800, image: "/spinach.png", brand: "غير محدد" },
            { id: 42, name: "زهرة", quantity: 1, unit: "كغ", minPrice: 3000, usdPrice: 0, avgPrice: 3500, image: "/cauliflower.png", brand: "غير محدد" },
            { id: 43, name: "باذنجان", quantity: 1, unit: "كغ", minPrice: 2500, usdPrice: 0, avgPrice: 2800, image: "/eggplant.png", brand: "غير محدد" },
        ],
    },

    {
        title: "المشروبات",
        products: [
            { id: 46, name: "مياه معدنية", quantity: 1, unit: "لتر", minPrice: 1000, usdPrice: 0, avgPrice: 1200, image: "/water.png", brand: "نستله" },
            { id: 47, name: "عصير برتقال", quantity: 1, unit: "لتر", minPrice: 5000, usdPrice: 0, avgPrice: 5500, image: "/orange_juice.png", brand: "سنكوال" },
            { id: 48, name: "عصير تفاح", quantity: 1, unit: "لتر", minPrice: 6000, usdPrice: 0, avgPrice: 6500, image: "/apple_juice.png", brand: "سنكوال" },
            { id: 49, name: "مشروب غازي", quantity: 1, unit: "لتر", minPrice: 3000, usdPrice: 0, avgPrice: 3500, image: "/soda.png", brand: "بيبسي" },
        ],
    },

    {
        title: "المعلبات",
        products: [
            { id: 54, name: "فاصوليا معلبة", quantity: 1, unit: "علبة", minPrice: 3000, usdPrice: 0, avgPrice: 3500, image: "/canned_beans.png", brand: "لونا" },
            { id: 55, name: "طماطم معلبة", quantity: 1, unit: "علبة", minPrice: 2500, usdPrice: 0, avgPrice: 2800, image: "/canned_tomatoes.png", brand: "لونا" },
            { id: 56, name: "ذرة حلوة معلبة", quantity: 1, unit: "علبة", minPrice: 2000, usdPrice: 0, avgPrice: 2200, image: "/canned_corn.png", brand: "غرين جايانت" },
            { id: 57, name: "تونة معلبة", quantity: 1, unit: "علبة", minPrice: 5000, usdPrice: 0, avgPrice: 5500, image: "/canned_tuna.png", brand: "هاف مون" },
            { id: 58, name: "سردين معلب", quantity: 1, unit: "علبة", minPrice: 4000, usdPrice: 0, avgPrice: 4500, image: "/canned_sardines.png", brand: "بريز" },
            { id: 59, name: "حليب مكثف محلى", quantity: 1, unit: "علبة", minPrice: 6000, usdPrice: 0, avgPrice: 6500, image: "/condensed_milk.png", brand: "نستله" },
            { id: 60, name: "معجون طماطم", quantity: 1, unit: "علبة", minPrice: 1500, usdPrice: 0, avgPrice: 1800, image: "/tomato_paste.png", brand: "لونا" },
        ],
    },

];